<?php

declare(strict_types=1);

return [
    'save_school' => 'action_save_school',
    'save_teacher' => 'action_save_teacher',
    'delete_teacher' => fn (): mixed => action_delete('teachers', 'teachers'),
    'save_class' => 'action_save_class',
    'delete_class' => fn (): mixed => action_delete('classes', 'classes'),
    'save_student' => 'action_save_student',
    'delete_student' => fn (): mixed => action_delete('students', 'students'),
    'save_subject' => 'action_save_subject',
    'delete_subject' => fn (): mixed => action_delete('subjects', 'subjects'),
    'save_assignment' => 'action_save_assignment',
    'delete_assignment' => fn (): mixed => action_delete('teaching_assignments', 'assignments'),
    'save_user' => 'action_save_user',
    'delete_user' => fn (): mixed => action_delete('users', 'users'),
    'save_profile' => 'action_save_profile',
    'save_grades' => 'action_save_grades',
    'save_student_attendance' => 'action_save_student_attendance',
    'save_teacher_attendance' => 'action_save_teacher_attendance',
    'save_teacher_attendance_self' => 'action_save_teacher_attendance_self',
    'save_promotion' => 'action_save_promotion',
    'generate_lesson_schedule' => 'action_generate_lesson_schedule',
    'save_lesson_schedule' => 'action_save_lesson_schedule',
    'delete_lesson_schedule' => 'action_delete_lesson_schedule',
    'save_schedule_grid' => 'action_save_schedule_grid',
    'save_schedule_request' => 'action_save_schedule_request',
    'delete_schedule_request' => 'action_delete_schedule_request',
    'save_journal' => 'action_save_journal',
    'delete_journal' => fn (): mixed => action_delete('daily_journals', 'journals'),
    'save_violation' => 'action_save_violation',
    'delete_violation' => fn (): mixed => action_delete('student_violations', 'violations'),
    'save_violation_rule' => 'action_save_violation_rule',
    'delete_violation_rule' => 'action_delete_violation_rule',
    'save_sp_threshold' => 'action_save_sp_threshold',
    'save_reward' => 'action_save_reward',
    'delete_reward' => 'action_delete_reward',

    'save_extracurricular' => 'action_save_extracurricular',
    'save_subject_group' => 'action_save_subject_group',
    'save_merged_subject' => 'action_save_merged_subject',
    'save_report_mapping' => fn (): mixed => action_save_report_mapping(),
    'save_signature' => 'action_save_signature',
    'save_report_date' => 'action_save_report_date',
    'save_student_photo' => 'action_save_student_photo',
    'bulk_student_photo' => 'action_bulk_student_photo',
    'save_cocurricular_theme' => 'action_save_cocurricular_theme',
    'save_cocurricular_activity' => 'action_save_cocurricular_activity',
    'save_cocurricular_group' => 'action_save_cocurricular_group',
    'save_learning_objective' => 'action_save_learning_objective',
    'save_extracurricular_scores' => 'action_save_extracurricular_scores',
    'save_graduation' => 'action_save_graduation',
    'import_certificate_numbers' => 'action_import_certificate_numbers',
    'save_transcript_settings' => fn (): mixed => action_save_settings('setting-transkrip'),
    'save_skl_settings' => fn (): mixed => action_save_settings('setting-skl'),
    'save_skl_mapping' => fn (): mixed => action_save_report_mapping('mapping-mapel-skl'),
    'save_final_scores' => 'action_save_final_scores',
    'create_backup' => 'action_create_backup',
    'restore_backup' => 'action_restore_backup',
    'save_whatsapp_settings' => 'action_save_whatsapp_settings',
    'save_whatsapp_guardian' => 'action_save_whatsapp_guardian',
    'save_whatsapp_template' => 'action_save_whatsapp_template',
    'queue_whatsapp_weekly' => 'action_queue_whatsapp_weekly',
    'send_whatsapp_queue' => 'action_send_whatsapp_queue',
    'cancel_whatsapp_queue' => 'action_cancel_whatsapp_queue',
    'queue_whatsapp_violation' => 'action_queue_whatsapp_violation',
    'queue_whatsapp_manual' => 'action_queue_whatsapp_manual',
    'save_dapodik_settings' => 'action_save_dapodik_settings',
    'generate_dapodik_bridge_token' => 'action_generate_dapodik_bridge_token',
    'import_dapodik_offline' => 'action_import_dapodik_offline',
    'sync_dapodik' => 'action_sync_dapodik',
    'send_dapodik' => 'action_send_dapodik',
    'delete_extended' => 'action_delete_extended',
    'import_bulk' => 'action_import_bulk',
    'import_bulk_validate' => 'action_import_bulk_validate',
    'import_bulk_confirm' => 'action_import_bulk_confirm',
    'bulk_delete' => 'action_bulk_delete',
];
