<?php

declare(strict_types=1);

return [
    'public' => [
        'install' => 'page_install',
        'login' => 'page_login',
        'logout' => 'page_logout',
        'lupa-password' => 'page_forgot_password',
        'telegram-register' => 'page_telegram_register',
        'telegram-web-login' => 'page_telegram_web_login',
    ],

    'private' => [
        'dashboard' => 'page_dashboard',
        'update-data' => 'page_update_data',
        'school' => 'page_school',
        'teachers' => 'page_teachers',
        'students' => 'page_students',
        'classes' => 'page_classes',
        'subjects' => 'page_subjects',
        'assignments' => 'page_assignments',
        'data-ekskul' => 'page_data_ekskul',
        'data-kelompok' => 'page_data_kelompok',
        'gabung-mapel' => 'page_gabung_mapel',
        'data-mapping' => 'page_data_mapping',
        'data-logo-ttd' => 'page_data_logo_ttd',
        'tanggal-rapor' => 'page_tanggal_rapor',
        'foto-siswa' => 'page_foto_siswa',
        'tema-kokurikuler' => 'page_tema_kokurikuler',
        'kegiatan-kokurikuler' => 'page_kegiatan_kokurikuler',
        'kelompok-kokurikuler' => 'page_kelompok_kokurikuler',
        'data-tp' => 'page_data_tp',
        'status-penilaian' => 'page_status_penilaian',
        'cetak-pelengkap-rapor' => fn (): mixed => page_print_document('cetak-pelengkap-rapor'),
        'cetak-nilai-rapor' => 'page_cetak_nilai_rapor_pdf',
        'rapor-generate-class' => 'page_rapor_generate_class',
        'rapor-generate-student' => 'page_rapor_generate_student',
        'rapor-download-student' => 'page_rapor_download_student',
        'rapor-download-class' => 'page_rapor_download_class',
        'biodata-generate-student' => 'page_biodata_generate_student',
        'biodata-download-student' => 'page_biodata_download_student',
        'biodata-generate-class' => 'page_biodata_generate_class',
        'biodata-download-class' => 'page_biodata_download_class',
        'cetak-leger-rapor' => fn (): mixed => page_print_document('cetak-leger-rapor'),
        'cetak-leger-pts' => fn (): mixed => page_print_document('cetak-leger-pts'),
        'cetak-nilai-rapor-pts' => fn (): mixed => page_print_document('cetak-nilai-rapor-pts'),
        'cetak-buku-induk' => fn (): mixed => page_print_document('cetak-buku-induk'),
        'input-kelulusan' => 'page_input_kelulusan',
        'import-nomor-ijazah' => 'page_import_nomor_ijazah',
        'setting-transkrip' => 'page_setting_transkrip',
        'setting-skl' => 'page_setting_skl',
        'mapping-mapel-skl' => fn (): mixed => page_data_mapping('Mapping Mapel SKL', 'mapping-mapel-skl'),
        'input-nilai-skl' => 'page_input_nilai_skl',
        'cetak-skl' => fn (): mixed => page_print_document('cetak-skl'),
        'cetak-transkrip-ijazah' => fn (): mixed => page_print_document('cetak-transkrip-ijazah'),
        'kirim-data-dapodik' => 'page_kirim_data_dapodik',
        'backup-restore' => 'page_backup_restore',
        'backup-download' => 'page_backup_download',
        'whatsapp' => 'page_whatsapp',
        'users' => 'page_users',
        'profile' => 'page_profile',
        'panduan' => 'page_panduan',
        'import-bulk' => 'page_import_bulk',
        'grades' => 'page_grades',
        'student-attendance' => 'page_student_attendance',
        'teacher-attendance' => 'page_teacher_attendance',
        'teacher-attendance-self' => 'page_teacher_attendance_self',
        'naik-kelas' => 'page_naik_kelas',
        'input-nilai-ekskul' => 'page_input_nilai_ekskul',
        'lesson-schedule' => 'page_lesson_schedule',
        'journals' => 'page_journals',
        'violations' => 'page_violations',
        'reports' => 'page_reports',
        'student-progress' => 'page_student_progress',
        'student-attendance-view' => 'page_student_attendance_view',
        'student-violations' => 'page_student_violations',
        'student-documents' => 'page_student_documents',
        'student-document-download' => 'page_student_document_download',
        'telegram' => 'page_telegram',
        'export-csv' => 'page_export_csv',
    ],
];
