SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE audit_logs;
TRUNCATE TABLE telegram_logs;
TRUNCATE TABLE telegram_registration_tokens;
TRUNCATE TABLE telegram_web_login_tokens;
TRUNCATE TABLE whatsapp_logs;
TRUNCATE TABLE whatsapp_queue;
TRUNCATE TABLE whatsapp_templates;
TRUNCATE TABLE whatsapp_guardians;
TRUNCATE TABLE lesson_schedule_reminder_logs;
TRUNCATE TABLE lesson_schedules;
TRUNCATE TABLE teacher_schedule_requests;
TRUNCATE TABLE student_attendance_entries;
TRUNCATE TABLE student_attendance_sessions;
TRUNCATE TABLE teacher_attendance;
TRUNCATE TABLE teacher_teaching_attendance;
TRUNCATE TABLE grades;
TRUNCATE TABLE final_scores;
TRUNCATE TABLE daily_journals;
TRUNCATE TABLE student_violations;
TRUNCATE TABLE student_photos;
TRUNCATE TABLE cocurricular_members;
TRUNCATE TABLE cocurricular_groups;
TRUNCATE TABLE cocurricular_activities;
TRUNCATE TABLE cocurricular_themes;
TRUNCATE TABLE extracurricular_members;
TRUNCATE TABLE extracurriculars;
TRUNCATE TABLE report_dates;
TRUNCATE TABLE report_mappings;
TRUNCATE TABLE merged_subjects;
TRUNCATE TABLE signatures;
TRUNCATE TABLE graduations;
TRUNCATE TABLE learning_objectives;
TRUNCATE TABLE teaching_assignments;
TRUNCATE TABLE students;
TRUNCATE TABLE classes;
TRUNCATE TABLE subjects;
TRUNCATE TABLE subject_groups;
TRUNCATE TABLE teachers;
TRUNCATE TABLE users;
TRUNCATE TABLE school_profile;
TRUNCATE TABLE dapodik_rombel_cache;
TRUNCATE TABLE dapodik_sync_logs;
TRUNCATE TABLE backups;
TRUNCATE TABLE app_settings;

SET FOREIGN_KEY_CHECKS = 1;
