CREATE TABLE IF NOT EXISTS school_profile (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  npsn VARCHAR(32) NULL,
  address TEXT NULL,
  principal_name VARCHAR(160) NULL,
  principal_nip VARCHAR(64) NULL,
  academic_year VARCHAR(32) NOT NULL,
  semester VARCHAR(32) NOT NULL,
  location_lat DECIMAL(10,8) NULL,
  location_lng DECIMAL(11,8) NULL,
  attendance_radius_meters INT NULL DEFAULT 500,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teachers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL,
  name VARCHAR(160) NOT NULL,
  nip VARCHAR(64) NULL,
  nuptk VARCHAR(64) NULL,
  gender VARCHAR(16) NULL,
  phone VARCHAR(32) NULL,
  email VARCHAR(160) NULL,
  position VARCHAR(120) NULL,
  telegram_chat_id VARCHAR(64) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS classes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL,
  name VARCHAR(80) NOT NULL,
  grade VARCHAR(16) NOT NULL,
  level VARCHAR(16) NULL,
  major VARCHAR(80) NULL,
  school_id INT UNSIGNED NULL,
  homeroom_teacher_id INT NULL,
  academic_year VARCHAR(32) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS students (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL,
  nis VARCHAR(64) NULL,
  nisn VARCHAR(64) NULL,
  name VARCHAR(160) NOT NULL,
  gender VARCHAR(16) NULL,
  birth_place VARCHAR(80) NULL,
  birth_date DATE NULL,
  religion VARCHAR(64) NULL,
  address TEXT NULL,
  phone VARCHAR(32) NULL,
  father_name VARCHAR(160) NULL,
  father_occupation VARCHAR(120) NULL,
  mother_name VARCHAR(160) NULL,
  mother_occupation VARCHAR(120) NULL,
  guardian_name VARCHAR(160) NULL,
  class_id INT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS subjects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL,
  name VARCHAR(160) NOT NULL,
  short_name VARCHAR(40) NULL,
  group_name VARCHAR(80) NULL,
  curriculum VARCHAR(32) NULL,
  kkm INT NULL,
  level VARCHAR(64) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teaching_assignments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL,
  teacher_id INT NOT NULL,
  class_id INT NOT NULL,
  subject_id INT NOT NULL,
  academic_year VARCHAR(32) NOT NULL,
  semester VARCHAR(32) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teacher_schedule_requests (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT NOT NULL,
  request_type VARCHAR(24) NOT NULL DEFAULT 'prefer',
  day_of_week INT NOT NULL,
  start_period INT NOT NULL DEFAULT 1,
  end_period INT NOT NULL DEFAULT 1,
  note TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lesson_schedules (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  teacher_id INT NOT NULL,
  class_id INT NOT NULL,
  subject_id INT NOT NULL,
  day_of_week INT NOT NULL,
  period_no INT NOT NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  note TEXT NULL,
  generated_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (class_id, day_of_week, period_no),
  UNIQUE (teacher_id, day_of_week, period_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lesson_schedule_reminder_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  schedule_id INT NOT NULL,
  teacher_id INT NOT NULL,
  telegram_chat_id VARCHAR(64) NOT NULL,
  reminder_date DATE NOT NULL,
  schedule_start_time TIME NOT NULL,
  reminder_minutes INT NOT NULL DEFAULT 10,
  message TEXT NULL,
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (schedule_id, reminder_date, schedule_start_time, reminder_minutes)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(160) NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'guru',
  teacher_id INT NULL,
  student_id INT NULL,
  telegram_chat_id VARCHAR(64) NULL,
  telegram_login_active TINYINT(1) NOT NULL DEFAULT 1,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learning_objectives (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject_id INT NOT NULL,
  grade VARCHAR(16) NOT NULL,
  description TEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS grades (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  student_id INT NOT NULL,
  score DECIMAL(5,2) NULL,
  description TEXT NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (assignment_id, student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS student_attendance_sessions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  date DATE NOT NULL,
  meeting_no INT NOT NULL DEFAULT 1,
  topic VARCHAR(255) NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (assignment_id, date, meeting_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS student_attendance_entries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id INT NOT NULL,
  student_id INT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'hadir',
  notes TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (session_id, student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teacher_attendance (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT NOT NULL,
  date DATE NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'hadir',
  time_in TIME NULL,
  time_out TIME NULL,
  notes TEXT NULL,
  recorded_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (teacher_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teacher_teaching_attendance (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  schedule_id INT NOT NULL,
  assignment_id INT NULL,
  teacher_id INT NOT NULL,
  class_id INT NOT NULL,
  subject_id INT NOT NULL,
  date DATE NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'hadir',
  time_in TIME NULL,
  time_out TIME NULL,
  notes TEXT NULL,
  recorded_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (schedule_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS student_violations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  date DATE NOT NULL,
  type VARCHAR(120) NOT NULL,
  description TEXT NULL,
  points INT NOT NULL DEFAULT 0,
  action_taken TEXT NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_guardians (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  name VARCHAR(160) NOT NULL,
  relationship VARCHAR(80) NULL,
  phone VARCHAR(32) NOT NULL,
  whatsapp_enabled TINYINT(1) NOT NULL DEFAULT 1,
  active TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_templates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  category VARCHAR(80) NOT NULL DEFAULT 'utility',
  body TEXT NOT NULL,
  cloud_template_name VARCHAR(160) NULL,
  language_code VARCHAR(16) NOT NULL DEFAULT 'id',
  parameter_keys TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_queue (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT NULL,
  guardian_id INT NULL,
  template_id INT NULL,
  message_type VARCHAR(40) NOT NULL,
  context_key VARCHAR(160) NULL,
  report_start DATE NULL,
  report_end DATE NULL,
  phone VARCHAR(32) NOT NULL,
  message TEXT NOT NULL,
  template_variables TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  scheduled_at DATETIME NULL,
  sent_at DATETIME NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  queue_id INT NULL,
  student_id INT NULL,
  guardian_id INT NULL,
  phone VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  provider_message_id VARCHAR(160) NULL,
  response_code INT NULL,
  response_body TEXT NULL,
  error_message TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_journals (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  teacher_id INT NOT NULL,
  class_id INT NOT NULL,
  subject_id INT NOT NULL,
  date DATE NOT NULL,
  meeting_no INT NOT NULL DEFAULT 1,
  topic VARCHAR(255) NOT NULL,
  activities TEXT NOT NULL,
  materials TEXT NULL,
  obstacles TEXT NULL,
  follow_up TEXT NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telegram_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  chat_id VARCHAR(64) NOT NULL,
  username VARCHAR(160) NULL,
  message TEXT NULL,
  response TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telegram_registration_tokens (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(96) NOT NULL UNIQUE,
  chat_id VARCHAR(64) NOT NULL,
  from_username VARCHAR(160) NULL,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telegram_web_login_tokens (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(96) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  next_page VARCHAR(80) NOT NULL DEFAULT 'dashboard',
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  action VARCHAR(120) NOT NULL,
  description TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS extracurriculars (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL,
  class_name VARCHAR(120) NOT NULL,
  type VARCHAR(80) NULL,
  name VARCHAR(160) NOT NULL,
  teacher_id INT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS extracurricular_members (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  extracurricular_id INT NOT NULL,
  student_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (extracurricular_id, student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dapodik_rombel_cache (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dapodik_id VARCHAR(64) NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  kind VARCHAR(80) NULL,
  grade VARCHAR(16) NULL,
  major VARCHAR(80) NULL,
  academic_year VARCHAR(32) NULL,
  teacher_id INT NULL,
  is_regular TINYINT(1) NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS subject_groups (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(120) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'aktif',
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merged_subjects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  grade VARCHAR(16) NOT NULL,
  source_subject_id INT NOT NULL,
  target_subject_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS report_mappings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  curriculum VARCHAR(80) NOT NULL,
  grade VARCHAR(16) NOT NULL,
  subject_id INT NOT NULL,
  group_id INT NULL,
  display_order INT NOT NULL DEFAULT 0,
  include_in_report TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS signatures (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(40) NOT NULL,
  user_id INT NULL,
  title VARCHAR(120) NULL,
  person_name VARCHAR(160) NULL,
  nip VARCHAR(64) NULL,
  file_path VARCHAR(255) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS report_dates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  grade VARCHAR(16) NOT NULL,
  report_date DATE NOT NULL,
  homeroom_place VARCHAR(80) NULL,
  principal_place VARCHAR(80) NULL,
  note TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS student_photos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cocurricular_themes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'aktif',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cocurricular_activities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  theme_id INT NOT NULL,
  phase VARCHAR(32) NOT NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT NULL,
  objective TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cocurricular_groups (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  grade VARCHAR(16) NOT NULL,
  phase VARCHAR(32) NOT NULL,
  theme_id INT NULL,
  coordinator_teacher_id INT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cocurricular_members (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  group_id INT NOT NULL,
  student_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (group_id, student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS graduations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'lulus',
  certificate_no VARCHAR(120) NULL,
  transcript_no VARCHAR(120) NULL,
  graduation_date DATE NULL,
  notes TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS final_scores (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  subject_id INT NOT NULL,
  score DECIMAL(5,2) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id, subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(120) NOT NULL UNIQUE,
  setting_value TEXT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dapodik_sync_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mode VARCHAR(40) NOT NULL,
  data_type VARCHAR(80) NOT NULL,
  endpoint VARCHAR(255) NULL,
  status VARCHAR(40) NOT NULL,
  message TEXT NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backups (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(180) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'ready',
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
